server:
  port: 8082

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5433/customers
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

axon:
  axonserver:
    enabled: false   # no Axon Server
  kafka:
    bootstrap-servers: localhost:9092
    client-id: customer-service
    default-topic: axon.events

    consumer:
      event-processor-mode: subscribing
      group-id: customer-service-group

    properties:
      "[key.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
      "[value.deserializer]": org.apache.kafka.common.serialization.ByteArrayDeserializer
      "[enable.auto.commit]": true
      "[auto.commit.interval.ms]": 3000
      "[auto.offset.reset]": earliest

  serializer:
    general: jackson
    events: jackson
    messages: jackson


