services:
  postgres:
    image: postgres:18
    container_name: postgres-customers
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: customers
    ports:
      - "5433:5432"
